//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file was automatically generated by RisohEditor.
// txt2qr_res.rc

#define IDC_STATIC                          -1

#define IDD_MAIN                            100

#define IDI_MAIN                            100

#define IDR_POPUP                           100

#define IDS_APPNAME                         100
#define IDS_VERSIONINFO                     101
#define IDS_SAVEFAIL                        102
#define IDS_EXECFAIL                        103
#define IDS_COPYFAIL                        104
#define IDS_INPUTTEXT                       105
#define IDS_COPYED                          106
#define IDS_COPY                            107
#define IDS_PNGFILTER                       108
#define IDS_SAVEIMGAS                       109
#define IDS_FILETOOLARGE                    110
#define IDS_CANTOPENFILE                    111
#define IDS_CHARACTERS                      112

#define ID_COPY                             100

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    101
        #define _APS_NEXT_COMMAND_VALUE     101
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
